services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
